function Utils:StartRace()
    BeginScaleformMovieMethod(self.Scaleform, 'START_RACE')
    ScaleformMovieMethodAddParamFloat(5000.0) -- Finish line position (when > (~1200) = outside of screen ?)
    ScaleformMovieMethodAddParamInt(1)
    ScaleformMovieMethodAddParamInt(1)
    ScaleformMovieMethodAddParamInt(2)
    ScaleformMovieMethodAddParamInt(3)
    ScaleformMovieMethodAddParamInt(4)
    ScaleformMovieMethodAddParamInt(5)
    ScaleformMovieMethodAddParamInt(6)
    ScaleformMovieMethodAddParamFloat(1000.0)
    ScaleformMovieMethodAddParamBool(false)
    EndScaleformMovieMethod()
end